feat: attempt to fix bug when merging

diff --git a/.githooks/prepare-commit-msg b/.githooks/prepare-commit-msg
--- a/.githooks/prepare-commit-msg
+++ b/.githooks/prepare-commit-msg
@@ -11,6 +11,22 @@ OUTPUT=""
 
 GIT='git --git-dir='$PWD'/.git'
 
+if [[ $2 == "merge" ]];
+then
+    if [[ $CURRBRANCH == "master" || $CURRBRANCH == "development" ]];
+    then
+        echo ""
+        echo -e "\t${RED}Cannot merge into $CURRBRANCH"
+        echo -e "\t${WHITE}First push the local branch to origin : git push -u origin"
+        echo e- "\tFrom there open a pull request to merge into development and asign 1 devops and your scrum master"
+        echo ""
+
+        $GIT reset --merge
+
+        exit 1
+    fi
+fi
+
 if [[ $CURRBRANCH =~ "feature/" ]];
 then
     OUTPUT="feat: $FILE_CONTENT"
@@ -26,22 +42,6 @@ else
     echo -e "\tTo rename a current branch : git branch -m <newname>"
 
     exit 1
-fi
-
-if [[ $2 == "merge" ]];
-then
-    if [[ $CURRBRANCH == "master" || $CURRBRANCH == "development" ]];
-    then
-        echo ""
-        echo -e "\t${RED}Cannot merge into $CURRBRANCH"
-        echo -e "\t${WHITE}First push the local branch to origin : git push -u origin"
-        echo e- "\tFrom there open a pull request to merge into development and asign 1 devops and your scrum master"
-        echo ""
-
-        $GIT reset --merge
-
-        exit 1
-    fi
 fi
 
 echo $OUTPUT > $1
