feat: party protected .githooks

diff --git a/.githooks/prepare-commit-msg b/.githooks/prepare-commit-msg
--- a/.githooks/prepare-commit-msg
+++ b/.githooks/prepare-commit-msg
@@ -26,6 +26,20 @@ else
     exit 1
 fi
 
+if [[ $2 == "merge" ]];
+then
+    if [[ $CURRBRANCH == "master" || $CURRBRANCH == "development" ]];
+    then
+        echo ""
+        echo -e "\t${RED}Cannot merge into $CURRBRANCH"
+        echo -e "\t${WHITE}First push the local branch to origin : git push -u origin"
+        echo e- "\tFrom there open a pull request to merge into development and asign 1 devops and your scrum master"
+        echo ""
+
+        exit 1
+    fi
+fi
+
 echo $OUTPUT > $1
 
 exit 0
